#Should the plugin require players have permissions to swing the offhand items?
require_permission: false
#Accuracy: Lower numbers will result in more accurate striking of entities, but with more than a few players, it may increase server lag. 0.5 is pretty comfortable.
accuraccy: 0.5
#A list of allowed materials to be swung in the offhand.
offhand_materials:
  - 'DIAMOND_SWORD'
  - 'GOLDEN_SWORD'
  - 'IRON_SWORD'
  - 'STONE_SWORD'
  - 'WOODEN_SWORD'
  - 'DIAMOND_AXE'
  - 'GOLDEN_AXE'
  - 'IRON_AXE'
  - 'STONE_AXE'
  - 'WOODEN_AXE'
#A list of materials that will prevent the offhand from swinging when present in the main hand.
disallowed_materials:
  - 'COOKED_PORKCHOP'
  - 'COOKED_BEEF'