require_permission: false
offhand_materials:
  - 'DIAMOND_SWORD'
  - 'GOLDEN_SWORD'
  - 'IRON_SWORD'
  - 'STONE_SWORD'
  - 'WOODEN_SWORD'
  - 'DIAMOND_AXE'
  - 'GOLDEN_AXE'
  - 'IRON_AXE'
  - 'STONE_AXE'
  - 'WOODEN_AXE'