#Should the plugin require players have permissions to swing the offhand items?
require_permission: false
#A list of allowed materials to be swung in the offhand.
offhand_materials:
  - 'DIAMOND_SWORD'
  - 'GOLDEN_SWORD'
  - 'IRON_SWORD'
  - 'STONE_SWORD'
  - 'WOODEN_SWORD'
  - 'DIAMOND_AXE'
  - 'GOLDEN_AXE'
  - 'IRON_AXE'
  - 'STONE_AXE'
  - 'WOODEN_AXE'